version: "3.4"

services:
  nginx:
    container_name: reverse-proxy
    image: reverse-proxy:latest
    restart: unless-stopped 
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - reverseproxycerts:/etc/nginx/certs
      - reverseproxyvhosts:/etc/nginx/vhost.d
      - reverseproxyhtml:/usr/share/nginx/html

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: reverse-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - reverseproxycerts:/etc/nginx/certs
      - reverseproxyvhosts:/etc/nginx/vhost.d
      - reverseproxyhtml:/usr/share/nginx/html
  
volumes:
  reverseproxycerts:
  reverseproxyvhosts:
  reverseproxyhtml:

networks:
  default:
    external:
      name: reverse-proxy


